# Generated by Django 4.0.2 on 2022-02-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='password',
            field=models.CharField(default='name', max_length=30),
        ),
        migrations.AddField(
            model_name='person',
            name='username',
            field=models.CharField(default='name', max_length=30, unique=True),
        ),
    ]
