# Generated by Django 4.0.2 on 2022-02-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_person_gender_alter_person_postcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='male',
            field=models.BooleanField(default=True),
        ),
    ]
