# Generated by Django 4.0.2 on 2022-02-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_person_male'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcode', models.CharField(default='', max_length=7)),
                ('sport', models.CharField(default='', max_length=30)),
                ('mode', models.CharField(default='1v1', max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='password',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='person',
            name='username',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
    ]
