# Generated by Django 4.0.2 on 2022-02-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=30)),
                ('postcode', models.CharField(default='', max_length=6)),
                ('gender', models.BooleanField(default=True)),
                ('phone', models.CharField(default='', max_length=15)),
                ('age', models.IntegerField(default=20)),
                ('sport', models.CharField(default='', max_length=30)),
                ('experience', models.CharField(default='begginer', max_length=30)),
            ],
        ),
    ]
