# Generated by Django 4.0.2 on 2022-02-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_person_password_person_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='gender',
        ),
        migrations.AlterField(
            model_name='person',
            name='postcode',
            field=models.CharField(default='', max_length=7),
        ),
    ]
