# Generated by Django 4.0.3 on 2022-03-04 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teammatcherapp', '0007_mode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mode',
        ),
    ]
